# version: "3.9"

services:
  web:
    build: .
    ports:
      - "80:8000"
    environment:
      FLASK_APP: run.py
      FLASK_ENV: development
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app # mounting the /app on .
    env_file:
      - .env

  db:
    image: postgres:15
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_DB: nms_db
      POSTGRES_USER: nms_user
      POSTGRES_PASSWORD: vayvanna 
    volumes:
      - pgdata:/var/lib/postgresql/data # the volume mount, -> the /var/lib/psql/data stuff is mounted actly in the volume.
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # the init.sql path of psql is mounted on our docker host. on ./init.sql 
    healthcheck:
      test: ["CMD","pg_isready" ,"-d" ,"nms_db" ,"-U" ,"nms_user"]
      interval: 2s
      timeout: 5s
      retries: 5
volumes:
  pgdata: # the actual volume that we create, its only one and its for the pgdata (postgreSQL db), since we mounted its /var/lib/postgresql/data into it.
